countries:
- code: af
  name: Afghanistan
  region: south-asia
- code: ax
  name: Akrotiri
  region: europe
- code: al
  name: Albania
  region: europe
- code: ag
  name: Algeria
  region: africa
- code: aq
  name: American Samoa
  region: australia-oceania
- code: an
  name: Andorra
  region: europe
- code: ao
  name: Angola
  region: africa
- code: av
  name: Anguilla
  region: central-america-n-caribbean
- code: ay
  name: Antarctica
  region: antarctica
- code: ac
  name: Antigua and Barbuda
  region: central-america-n-caribbean
- code: ar
  name: Argentina
  region: south-america
- code: am
  name: Armenia
  region: middle-east
- code: aa
  name: Aruba
  region: central-america-n-caribbean
- code: at
  name: Ashmore and Cartier Islands
  region: australia-oceania
- code: as
  name: Australia
  region: australia-oceania
- code: au
  name: Austria
  region: europe
- code: aj
  name: Azerbaijan
  region: middle-east
- code: ba
  name: Bahrain
  region: middle-east
- code: um
  name: Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef,
    Midway Islands, Palmyra Atoll
  region: australia-oceania
- code: bg
  name: Bangladesh
  region: south-asia
- code: bb
  name: Barbados
  region: central-america-n-caribbean
- code: bo
  name: Belarus
  region: europe
- code: be
  name: Belgium
  region: europe
- code: bh
  name: Belize
  region: central-america-n-caribbean
- code: bn
  name: Benin
  region: africa
- code: bd
  name: Bermuda
  region: north-america
- code: bt
  name: Bhutan
  region: south-asia
- code: bl
  name: Bolivia
  region: south-america
- code: bk
  name: Bosnia and Herzegovina
  region: europe
- code: bc
  name: Botswana
  region: africa
- code: bv
  name: Bouvet Island
  region: antarctica
- code: br
  name: Brazil
  region: south-america
- code: io
  name: British Indian Ocean Territory
  region: south-asia
- code: vi
  name: British Virgin Islands
  region: central-america-n-caribbean
- code: bx
  name: Brunei
  region: east-n-southeast-asia
- code: bu
  name: Bulgaria
  region: europe
- code: uv
  name: Burkina Faso
  region: africa
- code: bm
  name: Burma
  region: east-n-southeast-asia
- code: by
  name: Burundi
  region: africa
- code: cv
  name: Cabo Verde
  region: africa
- code: cb
  name: Cambodia
  region: east-n-southeast-asia
- code: cm
  name: Cameroon
  region: africa
- code: ca
  name: Canada
  region: north-america
- code: cj
  name: Cayman Islands
  region: central-america-n-caribbean
- code: ct
  name: Central African Republic
  region: africa
- code: cd
  name: Chad
  region: africa
- code: ci
  name: Chile
  region: south-america
- code: ch
  name: China
  region: east-n-southeast-asia
- code: kt
  name: Christmas Island
  region: australia-oceania
- code: ip
  name: Clipperton Island
  region: north-america
- code: ck
  name: Cocos (Keeling) Islands
  region: australia-oceania
- code: co
  name: Colombia
  region: south-america
- code: cn
  name: Comoros
  region: africa
- code: cf
  name: Congo (Brazzaville)
  region: africa
- code: cw
  name: Cook Islands
  region: australia-oceania
- code: cr
  name: Coral Sea Islands
  region: australia-oceania
- code: cs
  name: Costa Rica
  region: central-america-n-caribbean
- code: hr
  name: Croatia
  region: europe
- code: cu
  name: Cuba
  region: central-america-n-caribbean
- code: uc
  name: Curacao
  region: central-america-n-caribbean
- code: cy
  name: Cyprus
  region: europe
- code: ez
  name: Czechia
  region: europe
- code: iv
  name: Côte d'Ivoire
  region: africa
- code: cg
  name: DRC
  region: africa
- code: da
  name: Denmark
  region: europe
- code: dx
  name: Dhekelia
  region: europe
- code: dj
  name: Djibouti
  region: africa
- code: do
  name: Dominica
  region: central-america-n-caribbean
- code: ec
  name: Ecuador
  region: south-america
- code: eg
  name: Egypt
  region: africa
- code: es
  name: El Salvador
  region: central-america-n-caribbean
- code: ek
  name: Equatorial Guinea
  region: africa
- code: er
  name: Eritrea
  region: africa
- code: en
  name: Estonia
  region: europe
- code: wz
  name: Eswatini
  region: africa
- code: et
  name: Ethiopia
  region: africa
- code: ee
  name: European Union
  region: europe
- code: fk
  name: Falkland Islands (Islas Malvinas)
  region: south-america
- code: fo
  name: Faroe Islands
  region: europe
- code: fm
  name: Federated States of Micronesia
  region: australia-oceania
- code: fj
  name: Fiji
  region: australia-oceania
- code: fi
  name: Finland
  region: europe
- code: fr
  name: France
  region: europe
- code: fp
  name: French Polynesia
  region: australia-oceania
- code: fs
  name: French Southern and Antarctic Lands
  region: antarctica
- code: gb
  name: Gabon
  region: africa
- code: gz
  name: Gaza, Gaza Strip
  region: middle-east
- code: gg
  name: Georgia
  region: middle-east
- code: gm
  name: Germany
  region: europe
- code: gh
  name: Ghana
  region: africa
- code: gi
  name: Gibraltar
  region: europe
- code: gr
  name: Greece
  region: europe
- code: gl
  name: Greenland
  region: north-america
- code: gj
  name: Grenada
  region: central-america-n-caribbean
- code: gq
  name: Guam
  region: australia-oceania
- code: gt
  name: Guatemala
  region: central-america-n-caribbean
- code: gk
  name: Guernsey
  region: europe
- code: gv
  name: Guinea
  region: africa
- code: pu
  name: Guinea-Bissau
  region: africa
- code: gy
  name: Guyana
  region: south-america
- code: ha
  name: Haiti
  region: central-america-n-caribbean
- code: hm
  name: Heard Island and McDonald Islands
  region: antarctica
- code: vt
  name: Holy See (Vatican City)
  region: europe
- code: ho
  name: Honduras
  region: central-america-n-caribbean
- code: hk
  name: Hong Kong
  region: east-n-southeast-asia
- code: hu
  name: Hungary
  region: europe
- code: ic
  name: Iceland
  region: europe
- code: in
  name: India
  region: south-asia
- code: id
  name: Indonesia
  region: east-n-southeast-asia
- code: ir
  name: Iran
  region: middle-east
- code: iz
  name: Iraq
  region: middle-east
- code: ei
  name: Ireland
  region: europe
- code: im
  name: Isle of Man
  region: europe
- code: is
  name: Israel
  region: middle-east
- code: it
  name: Italy
  region: europe
- code: jm
  name: Jamaica
  region: central-america-n-caribbean
- code: jn
  name: Jan Mayen
  region: europe
- code: ja
  name: Japan
  region: east-n-southeast-asia
- code: je
  name: Jersey
  region: europe
- code: jo
  name: Jordan
  region: middle-east
- code: kz
  name: Kazakhstan
  region: central-asia
- code: ke
  name: Kenya
  region: africa
- code: kr
  name: Kiribati
  region: australia-oceania
- code: kv
  name: Kosovo
  region: europe
- code: ku
  name: Kuwait
  region: middle-east
- code: kg
  name: Kyrgyzstan
  region: central-asia
- code: la
  name: Laos
  region: east-n-southeast-asia
- code: lg
  name: Latvia
  region: europe
- code: le
  name: Lebanon
  region: middle-east
- code: lt
  name: Lesotho
  region: africa
- code: li
  name: Liberia
  region: africa
- code: ly
  name: Libya
  region: africa
- code: ls
  name: Liechtenstein
  region: europe
- code: lh
  name: Lithuania
  region: europe
- code: lu
  name: Luxembourg
  region: europe
- code: mc
  name: Macau
  region: east-n-southeast-asia
- code: ma
  name: Madagascar
  region: africa
- code: mi
  name: Malawi
  region: africa
- code: my
  name: Malaysia
  region: east-n-southeast-asia
- code: mv
  name: Maldives
  region: south-asia
- code: ml
  name: Mali
  region: africa
- code: mt
  name: Malta
  region: europe
- code: rm
  name: Marshall Islands
  region: australia-oceania
- code: mr
  name: Mauritania
  region: africa
- code: mp
  name: Mauritius
  region: africa
- code: mx
  name: Mexico
  region: north-america
- code: md
  name: Moldova
  region: europe
- code: mn
  name: Monaco
  region: europe
- code: mg
  name: Mongolia
  region: east-n-southeast-asia
- code: mj
  name: Montenegro
  region: europe
- code: mh
  name: Montserrat
  region: central-america-n-caribbean
- code: mo
  name: Morocco
  region: africa
- code: mz
  name: Mozambique
  region: africa
- code: wa
  name: Namibia
  region: africa
- code: nr
  name: Nauru
  region: australia-oceania
- code: bq
  name: Navassa Island
  region: central-america-n-caribbean
- code: np
  name: Nepal
  region: south-asia
- code: nl
  name: Netherlands
  region: europe
- code: nc
  name: New Caledonia
  region: australia-oceania
- code: nz
  name: New Zealand
  region: australia-oceania
- code: nu
  name: Nicaragua
  region: central-america-n-caribbean
- code: ng
  name: Niger
  region: africa
- code: ni
  name: Nigeria
  region: africa
- code: ne
  name: Niue
  region: australia-oceania
- code: nf
  name: Norfolk Island
  region: australia-oceania
- code: kn
  name: North Korea
  region: east-n-southeast-asia
- code: mk
  name: North Macedonia
  region: europe
- code: cq
  name: Northern Mariana Islands
  region: australia-oceania
- code: 'no'
  name: Norway
  region: europe
- code: mu
  name: Oman
  region: middle-east
- code: pk
  name: Pakistan
  region: south-asia
- code: ps
  name: Palau
  region: australia-oceania
- code: pm
  name: Panama
  region: central-america-n-caribbean
- code: pp
  name: Papua New Guinea
  region: east-n-southeast-asia
- code: pf
  name: Paracel Islands
  region: east-n-southeast-asia
- code: pa
  name: Paraguay
  region: south-america
- code: pe
  name: Peru
  region: south-america
- code: rp
  name: Philippines
  region: east-n-southeast-asia
- code: pc
  name: Pitcairn Islands
  region: australia-oceania
- code: pl
  name: Poland
  region: europe
- code: po
  name: Portugal
  region: europe
- code: rq
  name: Puerto Rico
  region: central-america-n-caribbean
- code: qa
  name: Qatar
  region: middle-east
- code: ro
  name: Romania
  region: europe
- code: rs
  name: Russia
  region: central-asia
- code: rw
  name: Rwanda
  region: africa
- code: tb
  name: Saint Barthelemy
  region: central-america-n-caribbean
- code: sh
  name: Saint Helena, Ascension, and Tristan da Cunha
  region: africa
- code: sc
  name: Saint Kitts and Nevis
  region: central-america-n-caribbean
- code: st
  name: Saint Lucia
  region: central-america-n-caribbean
- code: rn
  name: Saint Martin
  region: central-america-n-caribbean
- code: sb
  name: Saint Pierre and Miquelon
  region: north-america
- code: vc
  name: Saint Vincent and the Grenadines
  region: central-america-n-caribbean
- code: ws
  name: Samoa
  region: australia-oceania
- code: sm
  name: San Marino
  region: europe
- code: tp
  name: Sao Tome and Principe
  region: africa
- code: sa
  name: Saudi Arabia
  region: middle-east
- code: sg
  name: Senegal
  region: africa
- code: ri
  name: Serbia
  region: europe
- code: se
  name: Seychelles
  region: africa
- code: sl
  name: Sierra Leone
  region: africa
- code: sn
  name: Singapore
  region: east-n-southeast-asia
- code: nn
  name: Sint Maarten
  region: central-america-n-caribbean
- code: lo
  name: Slovakia
  region: europe
- code: si
  name: Slovenia
  region: europe
- code: bp
  name: Solomon Islands
  region: australia-oceania
- code: so
  name: Somalia
  region: africa
- code: sf
  name: South Africa
  region: africa
- code: sx
  name: South Georgia and South Sandwich Islands
  region: south-america
- code: ks
  name: South Korea
  region: east-n-southeast-asia
- code: od
  name: South Sudan
  region: africa
- code: sp
  name: Spain
  region: europe
- code: pg
  name: Spratly Islands
  region: east-n-southeast-asia
- code: ce
  name: Sri Lanka
  region: south-asia
- code: su
  name: Sudan
  region: africa
- code: ns
  name: Suriname
  region: south-america
- code: sv
  name: Svalbard (sometimes referred to as Spitsbergen, the largest island in the
    archipelago)
  region: europe
- code: sw
  name: Sweden
  region: europe
- code: sz
  name: Switzerland
  region: europe
- code: sy
  name: Syria
  region: middle-east
- code: tw
  name: Taiwan
  region: east-n-southeast-asia
- code: ti
  name: Tajikistan
  region: central-asia
- code: tz
  name: Tanzania
  region: africa
- code: th
  name: Thailand
  region: east-n-southeast-asia
- code: xq
  name: The Arctic Ocean is
  region: oceans
- code: zh
  name: The Atlantic Ocean is
  region: oceans
- code: bf
  name: The Bahamas
  region: central-america-n-caribbean
- code: dr
  name: The Dominican
  region: central-america-n-caribbean
- code: ga
  name: The Gambia
  region: africa
- code: xo
  name: The Indian Ocean is
  region: oceans
- code: zn
  name: The Pacific Ocean is
  region: oceans
- code: tt
  name: Timor-Leste
  region: east-n-southeast-asia
- code: to
  name: Togo
  region: africa
- code: tl
  name: Tokelau
  region: australia-oceania
- code: tn
  name: Tonga
  region: australia-oceania
- code: td
  name: Trinidad and Tobago
  region: central-america-n-caribbean
- code: ts
  name: Tunisia
  region: africa
- code: tu
  name: Turkey
  region: middle-east
- code: tx
  name: Turkmenistan
  region: central-asia
- code: tk
  name: Turks and Caicos Islands
  region: central-america-n-caribbean
- code: tv
  name: Tuvalu
  region: australia-oceania
- code: ug
  name: Uganda
  region: africa
- code: up
  name: Ukraine
  region: europe
- code: ae
  name: United Arab Emirates
  region: middle-east
- code: uk
  name: United Kingdom
  region: europe
- code: us
  name: United States
  region: north-america
- code: uy
  name: Uruguay
  region: south-america
- code: uz
  name: Uzbekistan
  region: central-asia
- code: nh
  name: Vanuatu
  region: australia-oceania
- code: ve
  name: Venezuela
  region: south-america
- code: vm
  name: Vietnam
  region: east-n-southeast-asia
- code: vq
  name: Virgin Islands
  region: central-america-n-caribbean
- code: wq
  name: Wake Island
  region: australia-oceania
- code: wf
  name: Wallis and Futuna
  region: australia-oceania
- code: we
  name: West Bank
  region: middle-east
- code: wi
  name: Western Sahara
  region: africa
- code: ym
  name: Yemen
  region: middle-east
- code: za
  name: Zambia
  region: africa
- code: zi
  name: Zimbabwe
  region: africa
