fields:
- json_path: Introduction.Background.text
  display_name: Background
  category: Introduction
- json_path: Geography.Location.text
  display_name: Location
  category: Geography
- json_path: Geography.Area - comparative.text
  display_name: Area - Comparative
  category: Geography
- json_path: Geography.Climate.text
  display_name: Climate
  category: Geography
- json_path: Geography.Geographic coordinates.text
  display_name: Geographic Coordinates
  category: Geography
- json_path: Geography.Coastline.text
  display_name: Coastline
  category: Geography
- json_path: Environment.Climate.text
  display_name: Climate
  category: Environment
- json_path: Geography.Map references.text
  display_name: Map References
  category: Geography
- json_path: Geography.Elevation.highest point.text
  display_name: Highest Point
  category: Geography
- json_path: Geography.Elevation.lowest point.text
  display_name: Lowest Point
  category: Geography
- json_path: Geography.Natural resources.text
  display_name: Natural Resources
  category: Geography
- json_path: Geography.Geography - note.text
  display_name: Geography - Note
  category: Geography
- json_path: Government.Country name.etymology.text
  display_name: Etymology
  category: Government
- json_path: Geography.Area.total .text
  display_name: Total
  category: Geography
- json_path: Geography.Land boundaries.total.text
  display_name: Total
  category: Geography
- json_path: Government.Country name.conventional long form.text
  display_name: Conventional Long Form
  category: Government
- json_path: Government.Country name.conventional short form.text
  display_name: Conventional Short Form
  category: Government
- json_path: Geography.Natural hazards.text
  display_name: Natural Hazards
  category: Geography
- json_path: Geography.Terrain.text
  display_name: Terrain
  category: Geography
- json_path: People and Society.Maternal mortality ratio.text
  display_name: Maternal Mortality Ratio
  category: People and Society
